CREATE TABLE `actor` (
  `actor_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(70) NOT NULL,
  `last_name` VARCHAR(70) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (actor_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

ALTER TABLE `actor` 
  ADD INDEX idx_actor_last_name(last_name);

GRANT CREATE, CREATE VIEW, DELETE, INSERT, SELECT, UPDATE ON TABLE actor TO 'JordanSanders'@'localhost';